name: Deploy AWS Notification System

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar credenciales de AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Desplegar la función Lambda
    - name: Deploy Lambda Function
      run: |
        zip function.zip lambda_function.py
        aws lambda update-function-code \
          --function-name procesador-notificaciones \
          --zip-file fileb://function.zip
