name: Deploy AWS Notification System
  
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar credenciales de AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-acces-key_id: ASIAYS2NTDS2MLIPFZVE
        aws-secret-acces_key: yKgh540+lMCbBWV7Gs4ru5hJc1wrh8109yF3zJfp
        aws-region: us-east-1

    # Desplegar la función Lambda
    - name: Deploy Lambda Function
      run: |
        zip function.zip index.mjs
        aws lambda update-function-code \
          --function-name proyecto2-emails \
          --zip-file fileb://function.zip
